---
title: "cdc-addm-time-trends"
author: "Alison Hill"
date: "April 1, 2016"
output:
  html_document:
    highlight: pygments
    theme: flatly
    smart: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warning = FALSE, error = FALSE, message = FALSE, tidy = FALSE, fig.path="figs/", echo = TRUE)
```

```{r echo = FALSE}
# load packages
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(ggplot2))) 
suppressWarnings(suppressMessages(library(tidyr)))
suppressWarnings(suppressMessages(library(readr)))
suppressWarnings(suppressMessages(library(ggthemes)))
suppressWarnings(suppressMessages(library(extrafont)))
suppressWarnings(suppressMessages(library(epitools)))
suppressWarnings(suppressMessages(library(scales)))
```

You'll need all the following packages installed first. [Here is a function](https://gist.github.com/stevenworthington/3178163) for doing this in one fell swoop:

```{r eval = FALSE}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}
```

```{r eval = FALSE}
# devtools::install_github("hadley/ggplot2") if you want subtitles/captions
pkgs <- c("readr", "dplyr", "tidyr", "ggplot2", "ggthemes") # list packages needed
ipak(pkgs) # take function, and give it that list
```

```{r}
# source file paths
source_cdc <- "/Users/hillali/Box Sync/hollander-practical-guide/data/cleaned_up_cdc_data/addm-since-2006.csv"

# load data files & keep var names
cdc <- read_csv(source_cdc, col_names = TRUE) # readr
```


```{r run_checks}
# check that prevalence is correct given n/n_total pop
check_overall_prev <- cdc %>%
  filter(strata == "overall") %>%
  mutate(check_prev_per_1k = round((n_asd/n_total)*1000, 1)) %>%
  select(site, n_total, n_asd, prev_per_1k, check_prev_per_1k, everything())

# check Poisson confidence intervals
# thanks joran http://stackoverflow.com/questions/29614849/dplyrmutate-to-add-multiple-values
# function to calculate cis
calc_ci  <- function(x, pt, site, strata, year){
  pois_ci <- pois.exact(x, pt)
  data_frame(site, strata, year, 
             lwr = round(pois_ci$lower*1000, 1),
             upr = round(pois_ci$upper*1000, 1))
}

check_ci <- check_overall_prev %>%
  group_by(n_asd, n_total) %>%
  do(calc_ci(.$n_asd, .$n_total, .$site, .$strata, .$year_survey)) %>%
  left_join(cdc) %>%
  select(site, n_total, n_asd, ends_with("per_1k"), lwr, upr, everything())

# check that, given prevalence and n_total pop for race/ethnic groups, n + CI make sense
check_nasd <- cdc %>%
  mutate(est_n_asd = round((prev_per_1k/1000)*n_total, 0)) %>%
  select(site, n_total, n_asd, est_n_asd, prev_per_1k, everything())
```


```{r desc_time_source}
# filter sites 
time_by_rec <- cdc %>%
  filter(!(site %in% c("Total", "Florida", "Pennsylvania")), strata == "overall")

time_by_rec %>%
  group_by(year_survey) %>%
  tally()
```


```{r survey-year-by-record-source}
cols <- c("#4878CF", "#6ACC65")
rec <- ggplot(time_by_rec) 
rec <- rec + geom_line(aes(group = for_line, x = year_survey, y = prev_per_1k, colour = data_source), lty = 3, lwd = .4) 
rec <- rec + geom_point(aes(x = year_survey, y = prev_per_1k, colour = data_source), size = 1.5) 
rec <- rec + geom_linerange(aes(x = year_survey, y = prev_per_1k, ymin = l95_per_1k, ymax = u95_per_1k,  colour = data_source), size = .5, alpha = .9) 
rec <- rec + facet_wrap(~ site) 
rec <- rec + scale_x_continuous(breaks = c(2006, 2008, 2010, 2012), name = "Survey Year") 
rec <- rec + scale_color_manual(values = cols, name = "Primary Record Source", labels = c("Educational + Health", "Health only")) 
rec <- rec + expand_limits(x = c(2005, 2013), y = 0) 
rec <- rec + scale_y_continuous(name = "Prevalence per 1000 children (95% CI)") 
rec <- rec + theme_hc(base_family = "Lato")  
rec <- rec + theme(panel.grid.major.y=element_line(size=.25))
rec <- rec + theme(axis.ticks.y = element_blank())
rec <- rec + theme(axis.ticks.length = unit(.1, "cm"))
rec <- rec + labs(title = "Prevalence of Autism Spectrum Disorder Among Children Aged 8 Years in the US by Record Source, 2006-2012")
rec <- rec + labs(subtitle = "Content source: CDC Autism and Developmental Disabilities Monitoring Network")
#rec <- rec + labs(caption = "Alison Presmanes Hill @apreshill")
rec <- rec + theme(plot.title=element_text(face="bold", size=9, margin=margin(b=6)))
rec <- rec + theme(plot.subtitle = element_text(size=8))
rec <- rec + theme(plot.caption = element_text(size=5, face = "italic", color = "darkgray"))
rec <- rec + theme(legend.text = element_text(margin=margin(r=-3), size=8))
rec <- rec + theme(legend.title = element_text(margin=margin(r=-3), size=8))
rec <- rec + theme(axis.title = element_text(margin=margin(r=-3), size=8))
rec <- rec + theme(axis.text = element_text(margin=margin(r=-3), size=6))
rec <- rec + theme(strip.text = element_text(margin=margin(t = 0, b = 0), lineheight = .01, size = 8))
rec
```


```{r}
# Saving 7.64 x 5.79 in image
rec_pdf <- "./figs/fig05_addm_survey_by_source.pdf"
ggsave(rec, file = rec_pdf, dpi = 600)
embed_fonts(rec_pdf, outfile = rec_pdf)

ggsave(rec, file = "./figs/thumbnail.png", dpi = 600)

rec_jpg <- "./figs/fig05_addm_survey_by_source.jpg"
ggsave(rec, file = rec_jpg, dpi = 600)
embed_fonts(rec_jpg)
```

```{r survey-year-by-race-ethnicity}
# filter sites 
race_eth <- c("white", "black", "hispanic")
time_by_reth <- cdc %>%
  filter(!(site %in% c("Total", "Florida", "Pennsylvania")), 
         strata %in% race_eth) %>%
  mutate(for_line = as.factor(for_line))

time_by_reth %>%
  group_by(strata, year_survey) %>%
  tally()

# reorder factor
levels(time_by_reth$strata) <- c("White", "Black", "Hispanic")
```

```{r}
cols <- c("#B47CC7", "#C4AD66", "#77BEDB","#D65F5F")
reth <- ggplot(time_by_reth) 
reth <- reth + geom_line(aes(group = for_line, x = year_survey, y = prev_per_1k, colour = strata), lty = 1, alpha = .5) 
reth <- reth + geom_point(aes(x = year_survey, y = prev_per_1k, colour = strata)) 
reth <- reth + facet_grid(strata ~ site) 
reth <- reth + scale_x_continuous(breaks = c(2006, 2008, 2010, 2012), name = "Survey Year") 
reth <- reth + scale_color_manual(values = cols, name = "reth/Ethnicity") 
reth <- reth + scale_fill_manual(values = cols) 
reth <- reth + expand_limits(x = c(2005, 2013), y = 0) 
reth <- reth + scale_y_continuous(name = "Prevalence per 1000 children (95% CI)") 
reth <- reth + theme_hc(base_family = "Lato")  
reth <- reth + theme(panel.grid.major.y=element_line(size=.25))
reth <- reth + theme(axis.ticks.y = element_blank())
reth <- reth + theme(axis.ticks.length = unit(.1, "cm"))
reth <- reth + labs(title = "Prevalence of Autism Spectrum Disorder Among Children Aged 8 Years in the US, 2006-2012")
reth <- reth + labs(subtitle = "Content source: CDC Autism and Developmental Disabilities Monitoring (ADDM) Network")
reth <- reth + labs(caption = "Alison Presmanes Hill @apreshill")
reth <- reth + theme(plot.title=element_text(face="bold", size=10, margin=margin(b=6)))
reth <- reth + theme(plot.subtitle = element_text(size=8))
reth <- reth + theme(plot.caption = element_text(size=8, face = "italic"))
reth <- reth + theme(legend.text = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(legend.title = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(axis.title = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(axis.text = element_text(margin=margin(r=-3), size=6))
reth <- reth + theme(strip.text = element_text(margin=margin(t = 0, b = 0), lineheight = .01, size = 8))
reth
```

```{r}
cols <- c("#C4AD66", "#77BEDB","#D65F5F","#B47CC7")
reth <- ggplot(time_by_reth) 
reth <- reth + geom_line(aes(group = interaction(strata, for_line), x = year_survey, y = prev_per_1k, colour = strata, alpha = data_source, size = data_source)) 
reth <- reth + geom_point(aes(x = year_survey, y = prev_per_1k, colour = strata, shape = data_source, fill = data_source)) 
reth <- reth + facet_wrap(~ site) 
reth <- reth + scale_x_continuous(breaks = c(2006, 2008, 2010, 2012), name = "Survey Year") 
reth <- reth + scale_color_manual(values = cols, name = "Race/Ethnicity", breaks = c("white", "black", "hispanic"), labels = c("White", "Black", "Hispanic")) 
reth <- reth + scale_fill_manual(values = c(NA, "white"), guide=FALSE) #fill points conditionally
reth <- reth + scale_alpha_manual(values = c(1, .6), name = "Primary Record Source", labels = c("Educational + Health", "Health only"))
reth <- reth + scale_size_manual(values = c(.5, .75), guide = FALSE)
reth <- reth + scale_shape_manual(values = c(16, 21), name = "Primary Record Source", labels = c("Educational + Health", "Health only")) # change shapes
reth <- reth + expand_limits(x = c(2005, 2013), y = 0) 
reth <- reth + scale_y_continuous(name = "Prevalence per 1000 children") 
reth <- reth + theme_hc(base_family = "Lato")  
reth <- reth + theme(panel.grid.major.y=element_line(size=.2))
reth <- reth + theme(axis.ticks.y = element_blank())
reth <- reth + theme(axis.ticks.length = unit(.1, "cm"))
reth <- reth + labs(title = "Prevalence of Autism Spectrum Disorder Among Children Aged 8 Years in the US by Race/Ethnicity, 2006-2012")
reth <- reth + labs(subtitle = "Content source: CDC Autism and Developmental Disabilities Monitoring Network")
#reth <- reth + labs(caption = "Alison Presmanes Hill @apreshill")
reth <- reth + theme(plot.title=element_text(face="bold", size=8, margin=margin(b=6)))
reth <- reth + theme(plot.subtitle = element_text(size=8))
reth <- reth + theme(plot.caption = element_text(size=5, face = "italic", colour = "darkgray"))
reth <- reth + theme(legend.text = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(legend.title = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(axis.title = element_text(margin=margin(r=-3), size=8))
reth <- reth + theme(axis.text = element_text(margin=margin(r=-3), size=6))
reth <- reth + theme(legend.key.height = unit(.1, "line"))
reth <- reth + theme(legend.box = "horizontal")
reth <- reth + guides(color=guide_legend(nrow=3,byrow=TRUE, title.position = "top", order = 1))
reth <- reth + guides(alpha=guide_legend(nrow=2,byrow=TRUE, title.position = "top", override.aes = list(fill = "white")))
reth <- reth + theme(strip.text = element_text(margin=margin(t = 0, b = 0), lineheight = .01, size = 8))
reth
```

```{r}
# Saving 7.64 x 5.03 in image
ggsave(reth, file = "/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.pdf", dpi = 600)
embed_fonts("/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.pdf",
outfile="/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.pdf")

ggsave(reth, file = "/Users/hillali/Documents/Projects/epidemiology-autism/figs/thumbnail2.png", dpi = 600)

ggsave(reth, file = "/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.jpg", dpi = 600)
embed_fonts("/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.jpg",
outfile="/Users/hillali/Box Sync/hollander-practical-guide/figs/addm_survey_by_reth.jpg")

```


